### ISSUE TITLE
Duplicate column name when unpacking

### ISSUE THREAD

**Issue by xeldarith** [TwoLaid/treeofsavior-tools#2]
When i try to unpack item_Equip.ies from ies.ipf to csv there are two column headers with same name "CoolDown" (duplicate column name).
Is it a bug?

**Comment by WillTheDoggy** [comment]
Did you expand the column names? 

![column name](http://puu.sh/mk4QW/cd956e027c.png "column")

**Comment by xeldarith** [comment]
That's a different column, there's another "Cooldown" column. iirc, it's
the last column.
Thanks.

**Comment by WillTheDoggy** [comment]
Interesting. There is another cooldown column in item_Equip.ies

But all 3 columns are blank (including the CoolDownGroup). I don't think its a bug, but rather it had an option before and they simply are not using it anymore. In item.ies, it doesn't have another CoolDown column.

**Comment by xeldarith** [comment]
Yeah i thought so too.

If i see the ies on IPFSuite, however, i see the two columns as CoolDown
and CoolDown_1.
But the extracted tsv file has two same "CoolDown" columns, different than
what's shown in the viewer.

So i wondered whether the script is unable to parse the '_' or it's really
a duplicate.
But the latter seems more logical now.

Thanks.
