### ISSUE TITLE
ies.py errors

### ISSUE THREAD

**Issue by pedrobj** [TwoLaid/treeofsavior-tools#4]
Getting some errors with ies.py

Command:
> ./ies.py ability.ies

Output:
> Traceback (most recent call last):
>   File "./ies.py", line 165, in <module>
>     ies = IesFile(sys.argv[1])
>   File "./ies.py", line 26, in __init__
>     self._open()
>   File "./ies.py", line 62, in _open
>     self.file_handle.seek(-self.resource_offset - self.data_offset, 2)
> IOError: [Errno 22] Invalid argument

Decrypting IPF files with [https://github.com/r1emu/IPFUnpacker](url)

**Comment by WillTheDoggy** [comment]
I believe IPFUnpacker already converts IES files to CSV but still has extension of .ies.  Try viewing it in notepad and see if it is not already converted.

**Comment by TwoLaid** [comment]
Let me know if @WillTheDoggy is correct, so I can close this. Otherwise, please upload your ability.ies somewhere and link it here

**Comment by pedrobj** [comment]
@WillTheDoggy is right, already CSV. I didn't see their changelog. o/ @WillTheDoggy @TwoLaid

**Comment by WillTheDoggy** [comment]
Cheers~

**Comment by TwoLaid** [comment]
Thanks @WillTheDoggy :)
